#! /bin/sh

# essential resources

pgrep -x sxhkd > /dev/null || sxhkd & # keybindings  
xrandr --output HDMI-0 --primary --mode 1920x1080 --rate 165 --rotate normal --output DP-0.8 --mode 2560x1440 --rotate left --right-of HDMI-0 & # monitor res
solaar --window=hide & # mouse battery
nitrogen --restore & # wallpaper
xset -dpms s off & # cursor size I think?
xsetroot -cursor_name left_ptr & # set cursor theme
polybar & # status bar
dunst & # notifications
blueman-applet & # bluetooth icon
xinput set-prop '9' 'libinput Accel Speed' -0.7 & # wireless sensitivity
xinput set-prop '14' 'libinput Accel Speed' -0.7 & # wired sensitivity
/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 & # polkit
picom --experimental-backends & # compositor
playerctld daemon & # control last used media
flameshot & # screen shots

# auto start applications

pavucontrol & # advanced volume control and fix hdmi audio delay
spotify & # music player
steam & # game launcher
vesktop & # discord client

# bspwm config

bspc monitor HDMI-0 -d  󰨞 󰈹 󰌆   󰙯 󰓓 󰺵 󰓇 󰋍 
bspc config border_width         2
bspc config window_gap          0
bspc config focused_border_color '#A4BF8B'
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true 
bspc config ignore_ewmh_focus true

# window rules

bspc rule -a Pavucontrol desktop='^11' 
bspc rule -a vlc state=floating
bspc rule -a Spotify desktop='^10'
bspc rule -a vesktop desktop='^7'
bspc rule -a steam desktop='^8'
bspc rule -a PrismLauncher desktop='^9' follow=on
bspc rule -a floorp desktop='^3' follow=on
bspc rule -a Code desktop='^2' follow=on
bspc rule -a kdenlive desktop='^6' follow=on
bspc rule -a KeePassXC desktop='^4' follow=on
bspc rule -a Virt-manager desktop='^5' follow=on
bspc rule -a Alacritty desktop='^1' follow=on
