#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
solaar --window=hide &
nitrogen --restore &
xrandr --output HDMI-0 --primary --mode 1920x1080 --rate 165 --rotate normal --output DP-0.8 --mode 2560x1440 --rotate left --right-of HDMI-0 &
xset -dpms s off &
xsetroot -cursor_name left_ptr &
#!/usr/bin/env sh 

# Terminate already running bar instances
killall -q polybar 

# Wait until the processes have been shut down
while pgrep -x polybar >/dev/null; do sleep 1; done

# Launch polybar
polybar &

/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &
flameshot &
picom &
pavucontrol &
playerctld daemon &
spotify &
steam &
vesktop &
bspc monitor HDMI-0 -d 1 2 3 4 5 6 󰙯 󰓓 󰺵 󰓇 󰋍 

bspc config border_width         2
bspc config window_gap          12
bspc config focused_border_color '#A4BF8B'

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config ignore_ewmh_focus true

bspc rule -a Pavucontrol desktop='^11' follow=off # I get audio delay unless I do this.
bspc rule -a vlc state=floating
bspc rule -a Spotify desktop='^10'
bspc rule -a vesktop desktop='^7'
bspc rule -a feh state=floating
bspc rule -a steam desktop='^8' follow=off
